# Generated by Django 3.0.4 on 2020-04-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20200411_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='app_blog/images/'),
        ),
    ]
